app/app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('autenticacion/', include("autenticacion.urls")),
    path('productos/', include("products.urls")),
    path('cart/', include("cart.urls")),
    path('orders/', include("orders.urls")),
]+ static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

app/cart/urls.py
from django.urls import path
from .views import *

app_name = "cart"

urlpatterns = [
    path('add_product/<int:producto_id>', add_producto, name='add_producto'),
    path('remove_product/<int:producto_id>', remove_producto, name='remove_producto'),
    path('decrement_product/<int:producto_id>', decrement_producto, name='decrement_producto'),
    path('clear', clear_cart, name='clear_cart'),


]

app/cart/models.py
from django.db import models

# Create your models here.

app/cart/views.py
from django.shortcuts import render,redirect
from products.models import Producto
from django.contrib.auth.decorators import login_required
from .cart import Cart

# Create your views here.


@login_required(login_url="/autenticacion/login")
def add_producto(request, producto_id):
    cart = Cart(request)
    producto = Producto.objects.get(id=producto_id)
    cart.add(producto=producto)
    return redirect("listado_productos")


@login_required(login_url="/autenticacion/login")
def remove_producto(request, producto_id):
    cart = Cart(request)
    producto = Producto.objects.get(id=producto_id)
    cart.remove(producto)
    return redirect("listado_productos")


@login_required(login_url="/autenticacion/login")
def decrement_producto(request, producto_id):
    cart = Cart(request)
    producto = Producto.objects.get(id=producto_id)
    cart.decrement(producto=producto)
    return redirect("listado_productos")


@login_required(login_url="/autenticacion/login")
def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect("listado_productos")

app/templates/cart/widget.html
{% load cart_tags %}
<table class="table table-bordered">
    <thead>
        <tr>
            <th colspan="3" class="text-center">
                Ventas
            </th>
        </tr>
        <tr>
            <th>Producto</th>
            <th>Cantidad</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% if request.session.cart.items %}
            {% for key, value in request.session.cart.items %}
                <tr class="text-center">
                    <td>{{ value.nombre }}</td>
                    <td>{{ value.existencia }}</td>
                    <td>
                        <a href="{% url 'cart:add_producto' value.producto_id %}"
                        class="btn btn-sm btn-success"
                        >
                            +
                        </a>
                        <a href="{% url 'cart:decrement_producto' value.producto_id %}"
                        class="ml-2 btn-sm btn-danger"
                        >
                            -
                        </a>
                        Total {{ value.precio|multiply:value.existencia|money_format:".0" }}
                    </td>
                </tr>
            {% endfor %}
        {% else %}
            <tr>
                <td colspan="3">
                    <div class="alert alert-danger text-center">
                        No tiene productos agregados
                    </div>
                </td>
            </tr>
        {% endif %}
    </tbody>
    <tfoot>
        <tr>
            <td colspan="3">
                Total: {{ cart_total_amount|money_format:".0" }}
            </td>
        </tr>
        {% if request.session.cart.items %}
            <tr>
                <td colspan="3">
                    <a href="{% url 'process_order' %}" class="btn btn-success">crear venta</a>
                </td>
            </tr>
        {% endif %}
    </tfoot>

</table>